#/*********************************************************************
# Copyright (c) Intel Corporation 2020
# SPDX-License-Identifier: Apache-2.0
#**********************************************************************/
{{- if .Values.console.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: console
  name: console
spec:
  ports:
  - port: 4433
    name: cira
    protocol: TCP
    targetPort: 4433
  - port: 3000
    name: webapi
    protocol: TCP
    targetPort: 3000
  selector:
    app: console
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  namespace: default
spec:
  replicas: {{ .Values.console.replicaCount }}
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      imagePullSecrets:
        - name: registrycredentials
      containers:
        - name: console
          image: {{ .Values.images.console }}
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 3000
            periodSeconds: 12
            timeoutSeconds: 12
            failureThreshold: 3
          env:
            - name: "CONSOLE_HEADLESS"
              value: "{{ .Values.console.headless }}"
            - name: "CONSOLE_LOG_LEVEL"
              value: "{{ .Values.console.logLevel }}"
            - name: "CONSOLE_COMMON_NAME"
              value: "{{ .Values.console.commonName }}"
            - name: "CONSOLE_CONNECTION_STRING"
              valueFrom:
                secretKeyRef:
                  name: console
                  key: connectionString
            - name: "CONSOLE_VAULT_ADDRESS"
              value: "http://{{ .Release.Name }}-vault:8200"
            - name: "CONSOLE_SECRETS_PATH"
              value: 'kv/data/'
            - name: "CONSOLE_PORT"
              value: '4433'
            - name: "CONSOLE_INSTANCE_NAME"
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: "CONSOLE_JWT_SECRET"
              valueFrom:
                secretKeyRef:
                  name: device-mgmt-toolkit-admin-jwt
                  key: secret
            - name: "CONSOLE_JWT_ISSUER"
              valueFrom:
                secretKeyRef:
                  name: device-mgmt-toolkit-admin-jwt
                  key: key
            - name: CONSOLE_WEB_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: consoleweb
                  key: user
            - name: CONSOLE_WEB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: consoleweb
                  key: password
            - name: CONSOLE_VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: vaultKey
          ports:
            - containerPort: 3000
              name: webapi
            - containerPort: 4433
              name: cira
{{- end }}
