#/*********************************************************************
# Copyright (c) Intel Corporation 2020
# SPDX-License-Identifier: Apache-2.0
#**********************************************************************/
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mps
  name: mps
spec:
  ports:
  - port: 4433
    name: cira
    protocol: TCP
    targetPort: 4433
  - port: 3000
    name: webapi
    protocol: TCP
    targetPort: 3000
  selector:
    app: mps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mps
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mps
  template:
    metadata:
      labels:
        app: mps
    spec:
      imagePullSecrets:
        - name: registrycredentials
      containers:
        - name: mps
          image: vprodemo.azurecr.io/mps:latest
          env:
            - name: "MPS_COMMON_NAME"
              value: "unknown"
            - name: "MPS_CONNECTION_STRING"
              value: "postgresql://postgresadmin:admin123@postgres:5432/mpsdb"
            - name: "MPS_VAULT_ADDRESS"
              value: "http://vault:8200"
          ports:
            - containerPort: 3000
              name: mps
            - containerPort: 4433
              name: mpsws