#/*********************************************************************
# Copyright (c) Intel Corporation 2020
# SPDX-License-Identifier: Apache-2.0
#**********************************************************************/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-mpswebserver
spec:
  replicas: {{ .Values.mps_web.replicaCount }}
  selector:
    matchLabels:
      app: azure-mpswebserver
  template:
    metadata:
      labels:
        app: azure-mpswebserver
    spec:
      imagePullSecrets:
        - name: {{ .Values.images.pullSecret }}
      containers:
      - name: azure-mpswebserver
        image: {{ .Values.images.mps }}
        env:
          - name: "GENERATE_SOURCEMAP"
            value: "false"
          - name: "MPS_HTTPS"
            value: "{{ .Values.mps.https }}"
          - name: "MPS_AUTH_ENABLED"
            value: "{{ .Values.mps_web.authEnabled }}"
          - name: "MPS_LOG_LEVEL"
            value: "{{ .Values.mps.logLevel }}"      
          - name: "MPS_GENERATE_CERTIFICATES"
            value: "{{ .Values.mps.generateCerts }}"
          - name: "MPS_NODE_ENV"
            value: "{{ .Values.mps.nodeEnv }}"
          - name: "MPS_COMMON_NAME"
            value: "{{ .Values.mps_web.staticIPAddress }}"
          - name: "MPS_STARTUP_MODE"
            value: "{{ .Values.mps_web.serverDeploymentMode }}"
          - name: "MPS_USE_ALLOWLIST"
            value: "{{ .Values.mps.useAllowList }}"
          - name: "MPS_PORT"
            value: "{{ .Values.mps.mpsPort }}"
          - name: "MPS_WEB_PORT"
            value: "{{ .Values.mps_web.webPort }}"
          - name: "MPS_USERNAME"
            value: "{{ .Values.mps.mpsUser }}"
          - name: "MPS_USE_GLOBAL_CREDENTIALS"
            value: "{{ .Values.mps.useGlobalCredentials }}"
          - name: "MPS_ENABLE_LOGGING"
            value: "{{ .Values.mps.enableLogging }}"
          - name: "MPS_DEBUG"
            value: "{{ .Values.mps.debug }}"
          - name: "MPS_USE_VAULT"
            value: "{{ .Values.mps.useVault }}"
          - name: "MPS_VAULT_ADDRESS"
            value : "{{ .Values.mps.vaultAddr }}"
          - name: "MPS_SECRETS_PATH"
            value: "{{ .Values.mps.secretsPath }}"
          - name: "MPS_DEBUG_LEVEL"
            value: "{{ .Values.mps.debugLevel }}"
          - name: "MPS_DISTRIBUTED_KV_PORT"
            value: "{{ .Values.mps.distributedKvPort }}"
          - name: "MPS_DISTRIBUTED_KV_NAME"
            value: "{{ .Values.mps.distributedKvName }}"
          - name: "MPS_WEB_PROXY_PORT"
            value: "{{ .Values.mps.webProxyPort }}"
          - name: "MPS_DISTRIBUTED_KV_IP"
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: "MPS_WEB_ADMIN_USER"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mpsSecretStoreNames.web }}
                key: {{ .Values.mps_web.webAdminUserKey }}
          - name: "MPS_WEB_ADMIN_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mpsSecretStoreNames.web }}
                key: {{ .Values.mps_web.webAdminPasswordKey }}
          - name: "MPS_PASS"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mpsSecretStoreNames.creds }}
                key: {{ .Values.mps.mpsPassword }}
          - name: MPS_MPSXAPIKEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mpsSecretStoreNames.api }}
                key: {{ .Values.mps.apikeyKeyName }}
          - name: MPS_CERT_FORMAT
            value: {{ .Values.mps.certFormat }}
          - name: MPS_TLS_CERT_CA
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mpsSecretStoreNames.certs }}
                key: {{ .Values.mps.mpscertca }}
          - name: MPS_TLS_CERT_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mpsSecretStoreNames.certs }}
                key: {{ .Values.mps.mpscertkey }}
          - name: MPS_TLS_CERT
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mpsSecretStoreNames.certs }}
                key: {{ .Values.mps.mpscertpublic }}
          - name: MPS_WEB_TLS_CERT
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mpsSecretStoreNames.webcerts }}
                key: {{ .Values.mps.webcertpublic }}
          - name: MPS_WEB_TLS_CERT_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mpsSecretStoreNames.webcerts }}
                key: {{ .Values.mps.webcertkey }}
          - name: MPS_WEB_TLS_CERT_CA
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mpsSecretStoreNames.webcerts }}
                key: {{ .Values.mps.webcertca }}
          - name: MPS_VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mpsSecretStoreNames.vault }}
                key: {{ .Values.mps.vaultkey }}
          - name: MPS_SESSION_ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mpsSecretStoreNames.session }}
                key: {{ .Values.mps.sessionEncryptionKey }}
          - name: "MPS_REDIS_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mpsSecretStoreNames.mpsrediscreds }}
                key: {{ .Values.mps_web.mpsrediscreds }}
          - name: "MPS_REDIS_HOST"
            value: "{{ .Values.mps_web.redisHost }}"
          - name: "MPS_REDIS_PORT"
            value: "{{ .Values.mps_web.redisPort }}"
          - name: "MPS_REDIS_ENABLE"
            value: "{{ .Values.mps_web.redisEnable }}"
          - name: "MPS_CORS_ORIGIN"
            value: "http://{{ .Values.ui.staticIPAddress }}"
        ports:
        - containerPort: {{ .Values.mps_web.webPort }}
          name: web