#/*********************************************************************
# Copyright (c) Intel Corporation 2020
# SPDX-License-Identifier: Apache-2.0
#**********************************************************************/
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: {{ .Values.mps.resourceGroupName }}
  name: azure-mps-load-balancer
spec:
  ports:
  - port: {{ .Values.mps.mpsPort }}
    name: mps
  loadBalancerIP: {{ .Values.mps.staticIPAddress }}
  type: LoadBalancer
  selector:
    app: azure-mpsserver
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: {{ .Values.mps_web.resourceGroupName }}
  name: azure-mps-web-load-balancer
spec:
  ports:
  - port: {{ .Values.mps_web.webPort }}
    name: web
  loadBalancerIP: {{ .Values.mps_web.staticIPAddress }}
  type: LoadBalancer
  selector:
    app: azure-mpswebserver
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: {{ .Values.rps.resourceGroupName }}
  name: azure-rps-load-balancer
spec:
  ports:
  - port: {{ .Values.rps.rpswsPort }}
    name: rps
  - port: {{ .Values.rps.rpswebPort }}
    name: rpsweb
  loadBalancerIP: {{ .Values.rps.staticIPAddress }}
  type: LoadBalancer
  selector:
    app: azure-rps
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: {{ .Values.ui.resourceGroupName }}
  name: azure-webui-load-balancer
spec:
  ports:
  - port: {{ .Values.ui.port }}
    name: ui
  loadBalancerIP: {{ .Values.ui.staticIPAddress }}
  type: LoadBalancer
  selector:
    app: azure-webui