#/*********************************************************************
# Copyright (c) Intel Corporation 2020
# SPDX-License-Identifier: Apache-2.0
#**********************************************************************/
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-file
  labels:
    app: nginx-conf 
data:
  nginx.conf: |-
{{ .Files.Get "nginx/nginx.conf" | indent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      imagePullSecrets:
        - name: {{ .Values.images.pullSecret }}
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-config-file
          items:
          - key: nginx.conf
            path: nginx.conf
      containers:
      - name: webui
        image: {{ .Values.images.ui }}
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: nginx.conf
        env:
          - name: "NODE_ENV"
            value: "production"
          - name: "MPS_SERVER"
            value: "https://localhost/mps"
          - name: "RPS_SERVER"
            value: "https://localhost/rps"
        ports:
        - containerPort: {{ .Values.ui.port }}
          name: ui