#/*********************************************************************
# Copyright (c) Intel Corporation 2020
# SPDX-License-Identifier: Apache-2.0
#**********************************************************************/
# Default values for installServersChart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images:
  mps: "vprodemo.azurecr.io/mps:latest"
  rps: "vprodemo.azurecr.io/rps:latest"
  webui: "vprodemo.azurecr.io/webui:latest"
  mpsrouter: "vprodemo.azurecr.io/mpsrouter:latest"
mps:
  commonName:
  # storageClassName: ""
  storageAccessMode: "ReadWriteOnce"
  replicaCount: 1
  logLevel: "silly"
  jwtExpiration: 1440
ui:
  replicaCount: 1
rps:
  replicaCount: 1
  logLevel: "silly"
vault:
  ui:
    enabled: "true"
    serviceType: "LoadBalancer"
kong:
  env:
    UPSTREAM_KEEPALIVE_POOL_SIZE: 0
  proxy:
    annotations:
      service.beta.kubernetes.io/azure-dns-label-name: ""
    stream:
      - containerPort: 4433
        servicePort: 4433
        parameters: []
mpsrouter:
  replicaCount: 1
