name: "Semantic Pull Request"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
permissions:
  contents: read

jobs:
  main:
    permissions:
      contents: read # for actions/checkout to fetch code
      pull-requests: read # for wagoid/commitlint-github-action to get commits in PR
    name: Validate PR and Commits
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - uses: amannn/action-semantic-pull-request@505e44b4f33b4c801f063838b3f053990ee46ea7 # v4.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@416045160973f9fff174ac6698412cfe7181c3f3 # v4.1.15
        with:
          configFile: .github/commitlint.config.js
